### ISSUE TITLE
Retorno almacenar

### ISSUE THREAD

**Issue by RazielC** [AlejandroSalinasV/Alejandro_Salinas_Victorino_objeto_seguro#1]
> El Método: almacenar_msj(msj: str) -> dict. Nos retorna como tal un diccionario, pero en si, ¿tiene caso este tipo de retorno?, ya que no se ocupa en otros metodos, o al menos aun no encuentro la relación de este tipo de retorno.

El retorno lo puedes dejar como esta indicado, en todo caso si no lo almacenas en una variable, el gabrage collector lo eliminara de la memoria, y a nosotros nos sirve para saber si los métodos están teniendo el comportamiento esperado.

**Comment by AlejandroSalinasV** [comment]
De acuerdo. Gracias.
