### ISSUE TITLE
Diccionario para llaves

### ISSUE THREAD

**Issue by RazielC** [AlejandroSalinasV/Alejandro_Salinas_Victorino_objeto_seguro#2]
> Genere un diccionario que es para colocar las llaves publicas de todos los objetos, de momento solo es parte estructural aunque podria ser un obejto. ¿Es valida esta implementación para el cambio de llaves?, o en su defecto, debo de implementar un metodo en clase Objeto seguro.

Así como lo resolviste es valido, ya que no se estableció algún mecanismo de intercambio de llave, aunque lo que segundo que mencionas acerca de hacerlo parte del objeto sería mucho mejor. Podrías crear un atributo que funcione como un monedero donde almacenas llaves publicas y que incluso este solo pueda ser accedido por el mismo objecto, sería un plus de seguridad.

**Comment by AlejandroSalinasV** [comment]
De acuerdo.
