### ISSUE TITLE
Método responder

### ISSUE THREAD

**Issue by RazielC** [AlejandroSalinasV/Alejandro_Salinas_Victorino_objeto_seguro#3]
> En el metodo Método: responder(msj: str) -> byte. Descripción: Este método se ejecuta automáticamente al recibir un saludo de otro objeto seguro, el parámetro de entrada es el nombre del objeto al que se responderá. La respuesta deber ser el mensaje recibido, concatenado con el string “MensajeRespuesta”.

Para este método considere que se deberia de cifrar el mensaje. Como se menciona es concatenar el mensaje: + , ¿es correcto? Otra cuestión, la descripción del metodo nos dice otra cosa de lo que se tiene escrito, ya que se deberia de enviar el nombre del objeto al que queremos responder, lo cual tiene sentido, entonces sería: responder(nombre: str) ->bytes: O en su defecto implemento responder(nombre: str, mensaje: str) ->bytes:

Es correcto, el mensaje debe ir cifrado. El método responder(msj: str) -> byte recibe un mensaje en claro el cual debe ser concatenado con el string "MensajeRespuesta" para luego ser cifrado con la llave pública del objeto al que vas a responder, esta cadena cifrada será el retorno de este método.

**Comment by AlejandroSalinasV** [comment]
De acuerdo.
