### ISSUE TITLE
Primer parte del proyecto

### ISSUE THREAD

**Issue by RazielC** [AlejandroSalinasV/Alejandro_Salinas_Victorino_objeto_seguro#4]
> ¿esta primera parte del proyecto solo se basa en realizar el enlace de comunicación de los 5 pasos que se muestran en el diagrama de la pag 3 del pdf, es decir del paso 0 al 4?

Esta parte del proyecto se evalúa con esos 5 pasos marcados en el diagrama, con esto se corrobora que se puede hacer una comunicación bidireccional segura.

**Comment by AlejandroSalinasV** [comment]
De acuerdo maestro.
