### ISSUE TITLE
RegistroMsj.txt

### ISSUE THREAD

**Issue by RazielC** [AlejandroSalinasV/Alejandro_Salinas_Victorino_objeto_seguro#5]
> ¿Es correcto suponer que al inciar un objeto su respectivo archivo de registros RegistoMsj_.txt debe generarse nuevamente, es decir, borrar historiales anteriores para que no existan conflictos de ID (ID repetidos)?

Es correcto, una buena práctica es que cuando se cierra el objeto seguro, se haga una limpieza de todos los archivos creados durante la ejecución del código, incluso con fines de seguridad.

**Comment by AlejandroSalinasV** [comment]
Vale. Gracias por responder todas mis dudas. Salu2.
